const quotes = [
  { q: "The only way to do great work is to love what you do.", a: "Steve Jobs" },
  { q: "Life is what happens when you're busy making other plans.", a: "John Lennon" },
  { q: "The future belongs to those who believe in the beauty of their dreams.", a: "Eleanor Roosevelt" },
  { q: "It is during our darkest moments that we must focus to see the light.", a: "Aristotle" },
  { q: "Whoever is happy will make others happy too.", a: "Anne Frank" },
  { q: "Do not go where the path may lead, go instead where there is no path and leave a trail.", a: "Ralph Waldo Emerson" },
  { q: "You will face many defeats in life, but never let yourself be defeated.", a: "Maya Angelou" },
  { q: "In the end, it's not the years in your life that count. It's the life in your years.", a: "Abraham Lincoln" },
  { q: "Never let the fear of striking out keep you from playing the game.", a: "Babe Ruth" },
  { q: "Life is either a daring adventure or nothing at all.", a: "Helen Keller" },
  { q: "Many of life's failures are people who did not realize how close they were to success when they gave up.", a: "Thomas A. Edison" },
  { q: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.", a: "Dr. Seuss" },
  { q: "Your time is limited, so don't waste it living someone else's life.", a: "Steve Jobs" },
  { q: "Not how long, but how well you have lived is the main thing.", a: "Seneca" },
  { q: "Money and success don't change people; they merely amplify what is already there.", a: "Will Smith" },
  { q: "If you want to live a happy life, tie it to a goal, not to people or things.", a: "Albert Einstein" },
  { q: "If you look at what you have in life, you'll always have more.", a: "Oprah Winfrey" },
  { q: "In three words I can sum up everything I've learned about life: it goes on.", a: "Robert Frost" },
  { q: "Love the life you live. Live the life you love.", a: "Bob Marley" },
  { q: "Be yourself; everyone else is already taken.", a: "Oscar Wilde" },
  { q: "I'm no hero. I put my buns on one leg at a time like everyone else.", a: "Bob Belcher" },
  { q: "I love you all, but I also love this burger, and right now the burger is winning.", a: "Bob Belcher" },
  { q: "We're a family, we fight and we love each other and sometimes we do both at the same time.", a: "Bob Belcher" },
  { q: "I consider myself a okay parent and a great cook.", a: "Bob Belcher" },
  { q: "If you believe in yourself and have enough money, your dreams can come true.", a: "Linda Belcher" },
  { q: "I'm not afraid of anything except bees and people not liking me.", a: "Linda Belcher" },
  { q: "All right, I'm gonna try to look sexy, but approachable.", a: "Linda Belcher" },
  { q: "I just want people to like me. Is that so wrong? It is? Okay.", a: "Linda Belcher" },
  { q: "I'm a smart, strong, sensual woman.", a: "Linda Belcher" },
  { q: "History is just future stuff that already happened.", a: "Louise Belcher" },
  { q: "I'm not afraid of hard work. I'm afraid of hard work not paying off.", a: "Louise Belcher" },
  { q: "I have a scheme and it's going to work this time because I've never tried it before.", a: "Louise Belcher" },
  { q: "The strong survive but the clever ones rule.", a: "Louise Belcher" },
  { q: "I'm ten and I've already peaked.", a: "Louise Belcher" },
  { q: "Why do today what you can put off until tomorrow and then forget about entirely?", a: "Gene Belcher" },
  { q: "I'm a hunter. I hunt things. Like the remote control.", a: "Gene Belcher" },
  { q: "Music is the one thing that nobody can take from me, mostly because it's in my head.", a: "Gene Belcher" },
  { q: "I'm not lazy, I'm energy efficient.", a: "Gene Belcher" },
  { q: "I'm a very important person with very important things to do.", a: "Gene Belcher" },
  { q: "I have a lot of feelings and I'm not afraid to eat them.", a: "Tina Belcher" },
  { q: "I'm no hero. I put my bra on one boob at a time like everyone else.", a: "Tina Belcher" },
  { q: "My heart just pooped its pants.", a: "Tina Belcher" },
  { q: "I'm a smart, strong, sensual woman and I'm not going to apologize for it.", a: "Tina Belcher" },
  { q: "If you need me I'll be in my room listening to sad music and eating crackers.", a: "Tina Belcher" },
  { q: "I'm not crying. I'm just sweating from my eyes.", a: "Tina Belcher" },
  { q: "Uhhhhh.", a: "Tina Belcher" },
]

export default quotes